### ISSUE TITLE
Not loading all groups

### ISSUE THREAD

**Issue by Moonie8t7** [leoherzog/googlegroupdirectoryunlister#1]
Hey Leo, just wanted to bring this to your attention.
For some reason, it stumbles on some groups (constantly stumbles on the same ones). I can't see a reason for it (screenshot, code and HTML attached).

![scriptErrorScreenshot](https://user-images.githubusercontent.com/43030636/161079728-346c014e-f887-4527-a1fa-7c11a2d5a00b.png)
[htmlindex.txt](https://github.com/leoherzog/googlegroupdirectoryunlister/files/8390390/htmlindex.txt)
[gscode.txt](https://github.com/leoherzog/googlegroupdirectoryunlister/files/8390391/gscode.txt)

**Comment by leoherzog** [comment]
Hrm! That's no good. Perhaps a rate limiting issue?

If you open the Developer Console (F12 in your web browser), do you see any specific errors?

**Comment by Moonie8t7** [comment]
> 

Nope - not that I can see. The weird thing is that the console shows it has completed it.
They all return 200 (see screenshot) on the network panel.

The only thing is that occasionally there are a few warnings about Unrecognized features, but everything else loads

![Screenshot 2022-04-01 141257](https://user-images.githubusercontent.com/43030636/161270665-3d1488fe-7f9d-4705-8a22-c4f6780afee6.png)
![Screenshot 2022-04-01 141506](https://user-images.githubusercontent.com/43030636/161271086-f09db2fc-ad41-472e-bd0b-65cb17b1bba4.png)
![Screenshot 2022-04-01 141611](https://user-images.githubusercontent.com/43030636/161271235-72e2a9c2-a68b-4cd5-bc34-342a01e6b82a.png)


Also I tried increasing the delay from 50ms to 1000ms with no effect, so not sure it is a rate limit issue.

I did once get the message: 
`ScriptError: GoogleJsonResponseException: API call to groupsSettings.groups.get failed with error: Invalid Value - but not sure why.`

**Comment by Moonie8t7** [comment]
Also, I tried increasing the delay from 50ms to 1000ms and that has had effect, so not sure its a ratelimiting thing

**Comment by leoherzog** [comment]
Do the same Groups continue to fail to load every time, or is it random which load correctly and which do not?

**Comment by Moonie8t7** [comment]
Always the same groups which is the weird thing. The groups are set up exactly the same as other groups that are loading, so no weird config there or anything

**Comment by leoherzog** [comment]
Could you create and run a new function at the top or the bottom of `code.gs` that looks like:

```js
function test() {
  console.log(JSON.stringify(getGroupSettings('groupid')));
}
```

(obviously with the `'groupid'` replaced with one of your broken groups) and paste the logged result (with whatever redacted info you'd like to redact)?

**Comment by Moonie8t7** [comment]
Here's the output:

`{"maxMessageBytes":26214400,"whoCanModerateContent":"OWNERS_AND_MANAGERS","whoCanHideAbuse":"NONE","whoCanDeleteAnyPost":"OWNERS_AND_MANAGERS","whoCanDeleteTopics":"OWNERS_AND_MANAGERS","whoCanBanUsers":"OWNERS_AND_MANAGERS","favoriteRepliesOnTop":"true","sendMessageDenyNotification":"false","whoCanUnassignTopic":"NONE","whoCanAssistContent":"NONE","whoCanAddReferences":"NONE","whoCanModerateMembers":"OWNERS_AND_MANAGERS","customReplyTo":"","whoCanModifyMembers":"OWNERS_AND_MANAGERS","whoCanJoin":"INVITED_CAN_JOIN","whoCanLockTopics":"OWNERS_AND_MANAGERS","includeInGlobalAddressList":"true","customRolesEnabledForSettingsToBeMerged":"false","messageModerationLevel":"MODERATE_NONE","whoCanMoveTopicsIn":"OWNERS_AND_MANAGERS","membersCanPostAsTheGroup":"false","includeCustomFooter":"false","whoCanMarkFavoriteReplyOnOwnTopic":"NONE","defaultSender":"DEFAULT_SELF","whoCanUnmarkFavoriteReplyOnAnyTopic":"NONE","showInGroupDirectory":"true","whoCanApproveMembers":"ALL_MANAGERS_CAN_APPROVE","messageDisplayFont":"DEFAULT_FONT","allowExternalMembers":"false","whoCanMarkDuplicate":"NONE","archiveOnly":"false","whoCanTakeTopics":"NONE","whoCanDiscoverGroup":"ALL_IN_DOMAIN_CAN_DISCOVER","replyTo":"REPLY_TO_IGNORE","whoCanMoveTopicsOut":"OWNERS_AND_MANAGERS","whoCanPostAnnouncements":"OWNERS_AND_MANAGERS","whoCanMakeTopicsSticky":"NONE","whoCanInvite":"ALL_MANAGERS_CAN_INVITE","email":"someGroupEmail@someDomain.com","whoCanAdd":"ALL_MANAGERS_CAN_ADD","whoCanEnterFreeFormTags":"NONE","allowGoogleCommunication":"false","whoCanMarkFavoriteReplyOnAnyTopic":"NONE","whoCanContactOwner":"ALL_OWNERS_CAN_CONTACT","customFooterText":"","defaultMessageDenyNotificationText":"","spamModerationLevel":"MODERATE","whoCanModifyTagsAndCategories":"NONE","allowWebPosting":"true","whoCanViewMembership":"ALL_MEMBERS_CAN_VIEW","enableCollaborativeInbox":"false","whoCanViewGroup":"ALL_OWNERS_CAN_VIEW","name":"Some Group Name","description":"Some Description","kind":"groupsSettings#groups","whoCanLeaveGroup":"ALL_MEMBERS_CAN_LEAVE","whoCanAssignTopics":"NONE","whoCanApproveMessages":"OWNERS_AND_MANAGERS","whoCanPostMessage":"ALL_OWNERS_CAN_POST","isArchived":"true","whoCanMarkNoResponseNeeded":"NONE"}`

**Comment by Moonie8t7** [comment]
And here is one from a working group:

`{"whoCanViewGroup":"ALL_MEMBERS_CAN_VIEW","whoCanViewMembership":"ALL_MEMBERS_CAN_VIEW","showInGroupDirectory":"true","email":"someWorkingGroupEmail@someDomain.com","favoriteRepliesOnTop":"true","whoCanModerateContent":"OWNERS_AND_MANAGERS","description":"Some Description","whoCanAdd":"ALL_MANAGERS_CAN_ADD","whoCanContactOwner":"ALL_IN_DOMAIN_CAN_CONTACT","whoCanEnterFreeFormTags":"NONE","whoCanPostAnnouncements":"OWNERS_AND_MANAGERS","name":"A Working Group","whoCanUnmarkFavoriteReplyOnAnyTopic":"NONE","whoCanInvite":"ALL_MANAGERS_CAN_INVITE","whoCanMarkFavoriteReplyOnAnyTopic":"NONE","replyTo":"REPLY_TO_IGNORE","whoCanJoin":"INVITED_CAN_JOIN","whoCanDiscoverGroup":"ALL_IN_DOMAIN_CAN_DISCOVER","whoCanBanUsers":"OWNERS_AND_MANAGERS","whoCanMoveTopicsIn":"OWNERS_AND_MANAGERS","allowGoogleCommunication":"false","whoCanTakeTopics":"NONE","whoCanModerateMembers":"OWNERS_AND_MANAGERS","includeInGlobalAddressList":"true","kind":"groupsSettings#groups","whoCanModifyMembers":"OWNERS_AND_MANAGERS","whoCanMakeTopicsSticky":"NONE","whoCanPostMessage":"ANYONE_CAN_POST","customReplyTo":"","includeCustomFooter":"false","whoCanUnassignTopic":"NONE","whoCanAssignTopics":"NONE","defaultSender":"DEFAULT_SELF","whoCanAssistContent":"NONE","whoCanAddReferences":"NONE","allowWebPosting":"true","isArchived":"true","whoCanMarkDuplicate":"NONE","membersCanPostAsTheGroup":"false","messageDisplayFont":"DEFAULT_FONT","whoCanApproveMembers":"ALL_MANAGERS_CAN_APPROVE","whoCanHideAbuse":"NONE","spamModerationLevel":"MODERATE","enableCollaborativeInbox":"false","customRolesEnabledForSettingsToBeMerged":"false","whoCanApproveMessages":"OWNERS_AND_MANAGERS","whoCanMoveTopicsOut":"OWNERS_AND_MANAGERS","whoCanLeaveGroup":"ALL_MEMBERS_CAN_LEAVE","maxMessageBytes":26214400,"messageModerationLevel":"MODERATE_NONE","whoCanLockTopics":"OWNERS_AND_MANAGERS","defaultMessageDenyNotificationText":"","whoCanDeleteAnyPost":"OWNERS_AND_MANAGERS","whoCanDeleteTopics":"OWNERS_AND_MANAGERS","sendMessageDenyNotification":"true","whoCanModifyTagsAndCategories":"NONE","customFooterText":"","archiveOnly":"false","allowExternalMembers":"false","whoCanMarkNoResponseNeeded":"NONE","whoCanMarkFavoriteReplyOnOwnTopic":"NONE"}`

**Comment by leoherzog** [comment]
Pretty sure I got there! It was breaking if the group's email address had a capital letter in it 😆. Try now!
